### PR TITLE
Add stylesheets

### PR DESCRIPTION
**Pull request by ajayakrishnan**
CSS file

### CODE REVIEW

**Review by ajayakrishnan — COMMENTED** [review]
PR looks good.

**Review by ajayakrishnan — COMMENTED** [review]
Good to go

**Review by ajayakrishnan — COMMENTED** [review]
Good to go

**Review by ajayakrishnan — COMMENTED** [review]
PR looks good.

**Review by aryakrishn — APPROVED** [review]
Verified

**Pull request merged**
